config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resource :writers, only: %i[edit update], module: 'articles'
  end

  resources :writers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :articles_writers, class_name: 'ArticleWriter', dependent: :destroy
  has_many :writers, through: :articles_writers

  accepts_nested_attributes_for :articles_writers, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true
end

app/models/article_writer.rb
class ArticleWriter < ApplicationRecord
  self.table_name = 'articles_writers'

  belongs_to :article
  belongs_to :writer

  validates :article_id, uniqueness: { scope: :writer_id }
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :articles_writers, class_name: 'ArticleWriter', dependent: :destroy
  has_many :articles, through: :articles_writers

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles/writers_controller.rb
module Articles
  class WritersController < ApplicationController
    before_action :set_article, only: %i[edit update]

    def edit
      @article.articles_writers.build
    end

    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        @article.articles_writers.build
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_article
      @article = Article.find(params[:article_id])
    end

    def article_params
      params.require(:article).permit(articles_writers_attributes: %i[id writer_id _destroy])
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title)
  end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :set_writer, only: %i[show edit update destroy]

  def index
    @writers = Writer.all
  end

  def show; end

  def new
    @writer = Writer.new
  end

  def edit; end

  def create
    @writer = Writer.new(writer_params)

    if @writer.save
      redirect_to @writer, notice: 'Writer was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @writer.update(writer_params)
      redirect_to @writer, notice: 'Writer was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @writer.destroy
    redirect_to writers_url, notice: 'Writer was successfully destroyed.'
  end

  private

  def set_writer
    @writer = Writer.find(params[:id])
  end

  def writer_params
    params.require(:writer).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
= form_for article do |f|
  - if article.errors.any?
    #error-explanation
      %h2 #{pluralize(article.errors.count, 'error')} prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form', article: @article

= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles
= link_to 'New Article', new_article_path

%table.table.table-striped.align-middle
  %thead
    %tr
      %th ID
      %th Title
      %th
      %th
      %th
      %th
      %th Write ID
      %th Write Name
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.id
        %td= article.title
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= button_to 'Destroy', article, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }
        %td= link_to 'Edit writers', edit_article_writers_path(article)
        %td
          - article.writers.each do |writer|
            %div= writer.id
        %td
          - article.writers.each do |writer|
            %div= writer.name
        %td
          - article.writers.each do |writer|
            %div= link_to 'Show', writer
        %td
          - article.writers.each do |writer|
            %div= link_to 'Edit', edit_writer_path(writer)

app/views/articles/new.html.haml
%h1 New article

= render 'form', article: @article

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p
  %b Title:
  = @article.title

%div
  %b Writers:
  %table.table.table-striped.align-middle
    %thead
      %tr
        %th ID
        %th Name
        %th
        %th

    %tbody
      - @article.writers.each do |writer|
        %tr
          %td= writer.id
          %td= writer.name
          %td= link_to 'Show', writer
          %td= link_to 'Edit', edit_writer_path(writer)

= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path
|
= link_to 'Edit writers', edit_article_writers_path(@article)

app/views/articles/writers/edit.html.haml
= form_with url: article_writers_path, method: 'patch', model: @article do |f|
  - if @article.errors.any?
    #error-explanation
      %h2 #{pluralize(@article.errors.count, 'error')} prohibited this article from being saved:
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message

  .field{ 'data-controller': 'fields-for' }
    %div{ 'data-fields-for-target': 'container' }
      = f.fields_for :articles_writers do |cf|
        %div
          = cf.label :writer_id, 'Writer ID'
          = cf.text_field :writer_id, readonly: cf.object.persisted?
          - if cf.object.persisted?
            = cf.label :_destroy
            = cf.check_box :_destroy
        - if cf.object.new_record?
          %template{ 'data-fields-for-target': 'template' }
            %div
              = cf.label :writer_id, 'Writer ID'
              = cf.text_field :writer_id
    %button{ type: 'button', 'data-action': 'fields-for#add' } Add input field
  .actions
    = f.submit 'Save'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title GithubActionsSandbox
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  %body
    %header.border-bottom
      .container
        %nav.navbar.navbar-expand-md
          .container-fluid
            = link_to 'Top', root_path, class: 'navbar-brand h1 mb-0'
            %button.navbar-toggler{ 'aria-controls': 'navbar-supported-content', 'aria-expanded': 'false',
              'aria-label': 'Toggle navigation', 'data-bs-target': '#navbar-supported-content',
              'data-bs-toggle': 'collapse', type: 'button' }
              %span.navbar-toggler-icon
            .collapse.navbar-collapse#navbar-supported-content
              %ul.navbar-nav.me-auto.mb-2.mb-md-0
                %li.nav-item= link_to 'Articles', articles_path, class: 'nav-link'
                %li.nav-item= link_to 'Writers', writers_path, class: 'nav-link'
    %main.container.py-3
      - flash.each do |_name, message|
        %p= message
      = yield

app/views/writers/_form.html.haml
= form_for writer do |f|
  - if writer.errors.any?
    #error-explanation
      %h2 #{pluralize(writer.errors.count, 'error')} prohibited this writer from being saved:
      %ul
        - writer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/writers/edit.html.haml
%h1 Editing writer

= render 'form', writer: @writer

= link_to 'Show', @writer
|
= link_to 'Back', writers_path

app/views/writers/index.html.haml
%h1 Listing writers
= link_to 'New Writer', new_writer_path

%table.table.table-striped.align-middle
  %thead
    %tr
      %th ID
      %th Name
      %th
      %th
      %th

  %tbody
    - @writers.each do |writer|
      %tr
        %td= writer.id
        %td= writer.name
        %td= link_to 'Show', writer
        %td= link_to 'Edit', edit_writer_path(writer)
        %td= button_to 'Destroy', writer, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }

app/views/writers/new.html.haml
%h1 New writer

= render 'form', writer: @writer

= link_to 'Back', writers_path

app/views/writers/show.html.haml
%p
  %b Name:
  = @writer.name

%div
  %b Articles:
  %table.table.table-striped.align-middle
    %thead
      %tr
        %th ID
        %th Title
        %th
        %th

    %tbody
      - @writer.articles.each do |article|
        %tr
          %td= article.id
          %td= article.title
          %td= link_to 'Show', article
          %td= link_to 'Edit', edit_article_path(article)

= link_to 'Edit', edit_writer_path(@writer)
|
= link_to 'Back', writers_path